name: Extract and Commit

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract files
        run: |
          unzip -o components.zip
          unzip -o node_modules.zip
          unzip -o services.zip

      - name: Remove zip files
        run: |
          rm components.zip
          rm node_modules.zip
          rm services.zip

      - name: Commit and push changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .
          git commit -m 'Extracted zip files and removed archives' || echo 'Nothing to commit'
          git push
